WIP: Adds support for module level test reporting
mbeddr/mps-build-backends pull request #3
Opened 2022-10-26 13:16 UTC by wjglerum

First rough sketch for reporting module level errors

Fixes #1

2022-10-26 13:58 UTC, wjglerum commented
Generated test report from before (notice that it does list the correct number of failures):
```xml
<testsuite name="model checking" tests="0" errors="0" failures="1" time="0" timestamp="2022-10-26T15:51:51"
           hostname="localhost">
    <properties/>
    <system-out></system-out>
    <system-err></system-err>
</testsuite>
```

Generated test report afterwards:
```xml
<testsuite name="model checking" tests="1" errors="0" failures="1" time="0" timestamp="2022-10-26T15:57:54"
           hostname="localhost">
    <properties/>
    <testcase name="module" classname="my.solution.with.module.errors" time="0">
        <failure message="&#xa; Can't find dependency: my.solution.non.existing [my.solution.with.module.errors]"
                 type="model checking"/>
    </testcase>
    <system-out></system-out>
    <system-err></system-err>
</testsuite>
```

2022-10-27 08:45 UTC, sergej-koscejev requested changes
We also need to bump the minor version (due to --format enhancement) and add some docs about the new things. And the changelog!

2022-10-27 08:45 UTC, sergej-koscejev commented on .gitignore
> +**/.mps/
Don't ignore .mps

2022-10-27 08:45 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheck.kt
> +            val allCheckedModules = itemsToCheck.modules // TODO do we need to filter anything ???
> do we need to filter anything ???

No, we don't.

2022-10-27 08:45 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheck.kt
> +    @Deprecated("Please use ONE_TEST_PER_MODULE_AND_MODEL instead")
```suggestion
    @Deprecated("Please use ONE_TEST_PER_MODULE_AND_MODEL instead, this doesn't report errors on modules.")
```

2022-10-27 08:45 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheck.kt
>              val testcases = oneTestCasePerModel(models, errorsPerModel, project)
Print a deprecation warning here to STDERR and also to the log.
The warning should tell the user what to do ("Use `--format=module`").

2022-10-27 08:45 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheckArgs.kt
> +    }.default(ReportFormat.ONE_TEST_PER_MODULE_AND_MODEL)
Leave the default as it was, for backwards compatibility.

2022-10-27 08:45 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheckArgs.kt
> +            "module" -> ReportFormat.ONE_TEST_PER_MODULE_AND_MODEL
Maybe this should be module-and-model or ...?

2022-10-27 08:47 UTC, sergej-koscejev commented on modelcheck/src/main/kotlin/ModelCheck.kt
> +            name = "module", // TODO which name to use here?
`"module " + it.moduleName`

2022-10-31 09:06 UTC, sergej-koscejev approved these changes

2022-10-31 09:06 UTC, merged

2022-10-31 09:13 UTC, sergej-koscejev commented
Looks good, merging. Thanks!